# Comments
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"

# Other 
array_width = 60